export const CONSTANTS = {
    FINMARKET_API: 'http://localhost:1001',

    DEFAULT_PERIOD: 30,

    TREND_DIRECTION_UP: 'Тренд вверх',
    TREND_DIRECTION_DOWN: 'Тренд вниз',

    VOLUME_DIRECTION_UP: 'Объем растет',
    VOLUME_DIRECTION_DOWN: 'Объем падает',

    CANDLE_SECUENCE_WHITE: 'Белые свечи',
    CANDLE_SECUENCE_BLACK: 'Черные свечи',

    RSI_INTERPRETATION_OVERBOUGHT: 'Перекупленность',
    RSI_INTERPRETATION_OVERSOLD: 'Перепроданность',

    DISPLAY_TYPE_STRING: 'String',
    DISPLAY_TYPE_NUMBER: 'Number',
    DISPLAY_TYPE_TICKER: 'Ticker',
    DISPLAY_TYPE_DATE: 'Date',
    DISPLAY_TYPE_PERCENT: 'Percent',
    DISPLAY_TYPE_RUBLE: 'Ruble',
    DISPLAY_TYPE_SECTOR: 'Sector',
    DISPLAY_TYPE_ANALYSE_RESULT_SUPERTREND: 'AnalyseResultSupertrend',
    DISPLAY_TYPE_ANALYSE_RESULT_CANDLE_SEQUENCE: 'AnalyseResultCandleSequence',
    DISPLAY_TYPE_ANALYSE_RESULT_CANDLE_VOLUME: 'AnalyseResultCandleVolume',
    DISPLAY_TYPE_ANALYSE_RESULT_RSI: 'AnalyseResultRsi',
    DISPLAY_TYPE_ANALYSE_RESULT_YIELD_LTM: 'AnalyseResultYieldLtm',

    COLOR_WHITE: '#FFFFFF',
    COLOR_RED: '#FF6633',
    COLOR_GREEN: '#00CC66',
    COLOR_YELLOW: '#FFFF99',
    COLOR_GRAY: '#D3D3D3',
    COLOR_DARKSLATEGRAY: '#2F4F4F',
    COLOR_STATEBLUE: '#6A5ACD'
}