export const SAGA_STRATEGY_SIGNALS = 'SAGA_STRATEGY_SIGNALS'
export const SAGA_BACKTEST_RESULTS = 'SAGA_BACKTEST_RESULTS'
export const SAGA_BACKTEST_RESULT_BY_ID = 'SAGA_BACKTEST_RESULT_BY_ID'

export const FETCH_STRATEGY_SIGNALS = 'FETCH_STRATEGY_SIGNALS'
export const FETCH_BACKTEST_RESULTS = 'FETCH_BACKTEST_RESULTS'
export const FETCH_BACKTEST_RESULT_BY_ID = 'FETCH_BACKTEST_RESULT_BY_ID'
