export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const SET_START_DATE = 'SET_START_DATE'
export const SET_END_DATE = 'SET_END_DATE'
export const SET_TICKER_LIST = 'SET_TICKER_LIST'
export const SET_TICKER = 'SET_TICKER'

export const SAGA_REPORT_SUPERTREND = 'SAGA_REPORT_SUPERTREND'
export const FETCH_REPORT_SUPERTREND = 'FETCH_REPORT_SUPERTREND'

export const SAGA_REPORT_CANDLE_SEQUENCE = 'SAGA_REPORT_CANDLE_SEQUENCE'
export const FETCH_REPORT_CANDLE_SEQUENCE = 'FETCH_REPORT_CANDLE_SEQUENCE'

export const SAGA_REPORT_CANDLE_VOLUME = 'SAGA_REPORT_CANDLE_VOLUME'
export const FETCH_REPORT_CANDLE_VOLUME = 'FETCH_REPORT_CANDLE_VOLUME'

export const SAGA_REPORT_RSI = 'SAGA_REPORT_RSI'
export const FETCH_REPORT_RSI = 'FETCH_REPORT_RSI'

export const SAGA_REPORT_DIVIDENDS = 'SAGA_REPORT_DIVIDENDS'
export const FETCH_REPORT_DIVIDENDS = 'FETCH_REPORT_DIVIDENDS'

export const SAGA_REPORT_BONDS = 'SAGA_REPORT_BONDS'
export const FETCH_REPORT_BONDS = 'FETCH_REPORT_BONDS'

export const SAGA_REPORT_STOCK = 'SAGA_REPORT_STOCK'
export const FETCH_REPORT_STOCK = 'FETCH_REPORT_STOCK'

export const SAGA_WATCH_LIST_TICKERS = 'SAGA_WATCH_LIST_TICKERS'
export const FETCH_WATCH_LIST_TICKERS = 'FETCH_WATCH_LIST_TICKERS'
